"""sync_latest_models

Revision ID: 560a2b3dab15
Revises: c504dfbe33e4
Create Date: 2026-01-24 23:15:46.729459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '560a2b3dab15'
down_revision: Union[str, Sequence[str], None] = 'c504dfbe33e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('dob', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('profession', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('morning_enabled', sa.Boolean(), nullable=True),
    sa.Column('morning_time', sa.String(), nullable=True),
    sa.Column('evening_enabled', sa.Boolean(), nullable=True),
    sa.Column('evening_time', sa.String(), nullable=True),
    sa.Column('fcm_token', sa.String(), nullable=True),
    sa.Column('push_enabled', sa.Boolean(), nullable=True),
    sa.Column('last_morning_summary_at', sa.String(), nullable=True),
    sa.Column('last_evening_summary_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_settings_id'), 'user_settings', ['id'], unique=False)
    op.create_index(op.f('ix_user_settings_user_id'), 'user_settings', ['user_id'], unique=True)
    op.add_column('tasks', sa.Column('raw_text', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('notified_10m', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('notified_20m', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('notified_due', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('notified_completion', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('notified_30m_post', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('last_nudged_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('med_timing', sa.String(), nullable=True))
    op.alter_column('tasks', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_foreign_key(None, 'tasks', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.alter_column('tasks', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.drop_column('tasks', 'med_timing')
    op.drop_column('tasks', 'last_nudged_at')
    op.drop_column('tasks', 'notified_30m_post')
    op.drop_column('tasks', 'notified_completion')
    op.drop_column('tasks', 'notified_due')
    op.drop_column('tasks', 'notified_20m')
    op.drop_column('tasks', 'notified_10m')
    op.drop_column('tasks', 'raw_text')
    op.drop_index(op.f('ix_user_settings_user_id'), table_name='user_settings')
    op.drop_index(op.f('ix_user_settings_id'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
