"""Add type column to tasks

Revision ID: c504dfbe33e4
Revises: 267f915d6d7c
Create Date: 2026-01-13 16:55:48.946319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c504dfbe33e4'
down_revision: Union[str, Sequence[str], None] = '267f915d6d7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('type', sa.String(), nullable=True))
    op.create_index(op.f('ix_tasks_type'), 'tasks', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_type'), table_name='tasks')
    op.drop_column('tasks', 'type')
    # ### end Alembic commands ###
